test: &default

  # Credentials for REST APIs
  client_id: AayYWFakMDtadw5byIaEqc4xuo9Hk83Xbr3MJvPDMAzElvTMBTQoLR7BtcZhcxGh13XISTjxzcR7zrv1
  client_secret: ENpFril_MtDdmlrXUe3iGKrut9fCQygRUu0g2_hkXO5wGD3fa3gIe3EWhNv0TX4Dz-RUeinfZS5cShVE

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  # <<: *default #commentar esta linea para produccion
  client_id: ATDBof8N8fpXD8rQ0gdD52KSfkBJsuNL6ZxmwmhiDggDDIb6cmqhBP-aWbRSO__DYlmCaZYPWMYfBzdK
  client_secret: EC2KClSLa1XEUJ9TNM7eKDNmHzk6XzURiyf2d4uaPeOrzG9DPhV4-G-Z2jL9-XmEm3mImmzPRBrAXJVH
  mode: live
